Ruby SDK Basic Implementation
wavefrontHQ/wavefront-sdk-ruby pull request #1
Opened 2018-12-19 13:37 UTC by yogeshprasad

This review request includes the basic implementation for Ruby SDK.
As of now it only allows users to send data via proxy.

2019-01-31 18:00 UTC, vikramraman approved these changes

2019-02-01 05:18 UTC, sushantdewan123 requested changes

2019-02-01 05:18 UTC, sushantdewan123 commented on common/proxy_connection_handler.rb
> +    def connect
Have @lock = Mutex.new in the ProxyConnectionHandler
and then do this
def connect
   @lock.synchronize do
      @reconnecting_socket = TCPSocket.open(@address, @port)
   end

2019-02-01 19:16 UTC, sushantdewan123 requested changes

2019-02-01 19:16 UTC, sushantdewan123 commented on common/proxy_connection_handler.rb
> +        @reconnecting_socket = TCPSocket.open(@address, @port)
one minor change - what if two threads get into synchronize block one after the other after checking initially that
@reconnecting_socket is nil.

so do this instead

@reconnecting_socket = TCPSocket.open(@address, @port) unless @reconnecting_socket.nil?

2019-02-04 19:45 UTC, sushantdewan123 approved these changes

2019-02-04 19:45 UTC, merged